import type { Metadata } from 'next'
import localFont from 'next/font/local'
import './styles/global.css'
import styles from './styles/layout.module.scss'

const pretendard = localFont({
  src: './fonts/PretendardVariable.woff2',
  display: 'swap',
  weight: '45 920',
  variable: '--font-pretendard',
})

export const metadata: Metadata = {
  title: 'SoyBank',
  description: 'Generated by create next app',
}

export default function RootLayout({
                                     children,
                                   }: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
    <body className={`${pretendard.variable} ${styles.container}`}>
    <section className={styles.wrapper}>
      {children}
    </section>
    </body>
    </html>
  )
}
